@startuml
start
:Get and parse HTML document;
:Create metadata model for each model defined in HTML;
:Generate .java models based on gathered metadata;
:Compile .java models;
:Parse constraints defined in HTML
against compiled .java models;
:Generate constraints as .aj files;
:Generate test cases;
stop
@enduml
