@startuml contester-component-diagram
package org.example.contester {
    [ContesterApplication]
}

package tudresden.ocl20.pivot {
    [standalone.facade]
}

package net.kanstren.osmo {
    [osmotester]
}

note top of net.kanstren.osmo
This is only used
when generating tests.
User can also provide tests manually
end note

note as htmlNote
Targeted HTML file must have
model and constraints defined
end note

file website.html {
}
file Model.java {
}
file ModelTests.java {
}
file "Constraints .aj files" as aj {
}

htmlNote .. website.html
htmlNote .. websiteUrl
websiteUrl <.. [ContesterApplication]: <<use>>
website.html <.. [ContesterApplication]: <<use>>
website.html <.> websiteUrl: <<or>>
[standalone.facade] <.. [ContesterApplication]: <<use>>
[osmotester] <.. [ContesterApplication]: <<use>>


[ContesterApplication] ..> Model.java: <<create>>
[ContesterApplication] ..> ModelTests.java: <<create>>
[ContesterApplication] ..> aj: <<create>>
@enduml